version: '3.7'

services:
  db:
    image: mysql:5.6
    container_name: db
    hostname: db
    environment:
      MYSQL_ROOT_PASSWORD: 12113  
      MYSQL_DATABASE: artworkdb  
    ports:
      - "28011:3306" 
    networks:
      - backend

  
  application:
    build:
      context: . 
      dockerfile: Dockerfile  
    environment:
      - DB_HOST=db  
      - DB_PORT=3306  
      - DB_USER=root  
      - DB_PASSWORD=12113  
    ports:
      - "8080:8080"  
    depends_on:
      - db  
    restart: always 
    networks:
      - backend


networks:
  backend:
    driver: bridge
